parteDe(latinoAmerica, continenteAmericano).
parteDe(estadosUnidosMexicanos, latinoAmerica).

parteDe(aguascalientes, estadosUnidosMexicanos).
parteDe(bajaCalifornia, estadosUnidosMexicanos).
parteDe(bajaCaliforniaSur, estadosUnidosMexicanos).
parteDe(campeche, estadosUnidosMexicanos).
parteDe(chiapas, estadosUnidosMexicanos).
parteDe(chihuahua, estadosUnidosMexicanos).
parteDe(cuahuila, estadosUnidosMexicanos).
parteDe(colima, estadosUnidosMexicanos).
parteDe(cdmx, estadosUnidosMexicanos).
parteDe(durango, estadosUnidosMexicanos).
parteDe(estadoDeMexico, estadosUnidosMexicanos).
parteDe(estadoDeMexico, estadosUnidosMexicanos).
parteDe(guanajuato, estadosUnidosMexicanos).
parteDe(guerrero, estadosUnidosMexicanos).
parteDe(hidalgo, estadosUnidosMexicanos).
parteDe(guadalajara, estadosUnidosMexicanos).
parteDe(michuacan, estadosUnidosMexicanos).
parteDe(morelos, estadosUnidosMexicanos).
parteDe(nayarit, estadosUnidosMexicanos).
parteDe(monterrey, estadosUnidosMexicanos).
parteDe(oaxaca, estadosUnidosMexicanos).
parteDe(puebla, estadosUnidosMexicanos).
parteDe(queretaro, estadosUnidosMexicanos).
parteDe(quintanaRoo, estadosUnidosMexicanos).
parteDe(sanLuisPotosi, estadosUnidosMexicanos).
parteDe(sinaloa, estadosUnidosMexicanos).
parteDe(sonora, estadosUnidosMexicanos).
parteDe(tabasco, estadosUnidosMexicanos).
parteDe(tamaulipas, estadosUnidosMexicanos).
parteDe(tlaxcala, estadosUnidosMexicanos).
parteDe(veracruz, estadosUnidosMexicanos).
parteDe(yucatan, estadosUnidosMexicanos).
parteDe(zacatecas, estadosUnidosMexicanos).

parteDe(aguascalientes, aguascalientes).
parteDe(mexicali, bajaCalifornia).
parteDe(laPaz, bajaCaliforniaSur).
parteDe(sanFranciscoDeCampeche, campeche).
parteDe(tuxtlaGutierrez, chiapas).
parteDe(chihuahua, chihuahua).
parteDe(saltillo, cuahuila).
parteDe(colima, colima).
parteDe(distritoFederal, cdmx).
parteDe(victoriaDeDurango, durango).
parteDe(tolucaDeLeerdo, estadoDeMexico).
parteDe(guanajuato, guanajuato).
parteDe(chilpansingoDelosBravo, guerrero).
parteDe(pachocaDeSoto, hidalgo).
parteDe(jalisco, guadalajara).
parteDe(morelia, michuacan).
parteDe(cuernavaca, morelos).
parteDe(tepic, nayarit).
parteDe(nuevoLeon, monterrey).
parteDe(oaxacaDeJuarez, oaxaca).
parteDe(pueblaDeZaragoza, puebla).
parteDe(santiagoDeQueretaro, querataro).
parteDe(chetumal, quintanaRoo).
parteDe(sanLuisPotosi, sanLuisPotosi).
parteDe(culiacanRosales, sinaloa).
parteDe(hermosillo, sonora).
parteDe(villahermosa, tabasco).
parteDe(ciudadVictoria, tamaulipas).
parteDe(tlaxcaladeXicohtencatl, tlaxcala).
parteDe(xalapaenriquez, veracruz).
parteDe(merida, yucatan).
parteDe(zacatecas, zacatecas).

partOf(X, Y):- parteDe(X, Y).
partOf(X, Y):- parteDe(X, Z), partOf(Z, Y).

municipios(aguascalientes, 11).
municipios(bajaCalifornia, 5).
municipios(bajaCaliforniaSur, 5).
municipios(campeche, 11).
municipios(chiapas, 118).
municipios(chihuahua, 67).
municipios(cuahuila, 38).
municipios(colima, 10).
municipios(cdmx, 16).
municipios(durango, 39).
municipios(estadoDeMexico, 125).
municipios(guanajuato, 46).
municipios(guerrero, 81).
municipios(hidalgo, 84).
municipios(guadalajara, 125).
municipios(michuacan, 113).
municipios(morelos, 33).
municipios(nayarit, 20).
municipios(monterrey, 51).
municipios(oaxaca, 570).
municipios(puebla, 217).
municipios(queretaro, 18).
municipios(quintanaRoo, 10).
municipios(sanLuisPotosi, 58).
municipios(sinaloa, 18).
municipios(sonora, 72).
municipios(tabasco, 17).
municipios(tamaulipas, 43).
municipios(tlaxcala, 60).
municipios(veracruz, 212).
municipios(yucatan, 106).
municipios(zacatecas, 58).

tieneAtrib(Ente, Atrib):- municipios(Ente, Atrib).
tieneAtrib(Ente, Atrib):- parteDe(Ente, EnteX), tieneAtrib(EnteX, Atrib).
